SweetsShop/Controllers/ProductsController.cs
using Microsoft.AspNet.Identity;
using SweetsShop.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SweetsShop.Controllers
{ 
    //[Authorize]
    public class ProductsController : Controller
    {
        private int _perPage = 3;
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Product
        //[Authorize(Roles = "User,Colaborator,Admin")]
        public ActionResult Index(string search)
        {
            //var products = db.Products.Include("Category").Include("User");
            ViewBag.butoaneSortari = true;
            //ViewBag.Products = products;
            if (search != null)
            {
                ViewBag.butoaneSortari = false;
                List<String> searchItems = new List<string>(search.Split(" .,?!()[]{};:".ToCharArray()));

                searchItems = searchItems.Where(s => !string.IsNullOrWhiteSpace(s)).ToList();
                var products = db.Products;
                List<Product> selectedProducts = new List<Product>();
                if (searchItems.Count() > 0)
                {
                    foreach (var product in products)
                    {
                        foreach (var item in searchItems.ToArray())
                        {
                            if (product.ProductName.Contains(item) || product.ProductDescription.Contains(item))
                            {
                                selectedProducts.Add(product);
                                break;
                            }
                        }
                    }
                }

                var totalItems = selectedProducts.Count();
                var currentPage = Convert.ToInt32(Request.Params.Get("page"));

                var offset = 0;

                if (!currentPage.Equals(0))
                {
                    offset = (currentPage - 1) * this._perPage;
                }

                var paginatedProducts = selectedProducts.Skip(offset).Take(this._perPage);

                ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)this._perPage);
                ViewBag.Products = paginatedProducts ;
                ViewBag.SearchString = search;
            }
            else
            {
                ViewBag.Products = db.Products.Include("Category").Include("User") ;
            }
            SetAccessRights();

            ViewBag.esteAdmin = User.IsInRole("Admin");
            ViewBag.esteColaborator = User.IsInRole("Colaborator");
            

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }
          
            
            return View();
        }

        // GET: Product
        //[Authorize(Roles = "User,Colaborator,Admin")]
        public ActionResult SortarePret(string search)
        {
            
            var products = db.Products.Include("Category").Include("User").OrderBy(a=> a.ProductPrice);
            ViewBag.Products = products;


            return View();
        }
        public ActionResult SortareRating(string search)
        {

            var products = db.Products.Include("Category").Include("User").OrderByDescending(a => a.ProductRating);
            ViewBag.Products = products;


            return View();
        }
        public ActionResult Requests()
        {
            var products = db.Products.Include("Category").Include("User");
            ViewBag.Products = products;
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult ValidateRequest(int id)
        {
            Product product = db.Products.Find(id);
            product.Request = true;
            if (ModelState.IsValid)
            {
                db.SaveChanges();
                TempData["message"] = "Ati aprobat produsul cu succes";
                
            }
            return Redirect(Request.UrlReferrer.ToString());
        }


        // GET: Show
        //[Authorize(Roles = "User,Colaborator,Admin")]
        public ActionResult Show(int id)
        {
            float rating = 0;
            Product product = db.Products.Find(id);
            var ratings = db.Comments.Where(d => d.ProductId.Equals(product.ProductId)).ToList();
            if (ratings.Count() > 0)
            {
                var ratingSum = ratings.Sum(d => d.Rating.Value);
                ViewBag.RatingSum = ratingSum;
                var ratingCount = ratings.Count(d=> d.Rating.Value>0);
                ViewBag.RatingCount = ratingCount;
                 rating = (ratingSum / ratingCount);
                ViewBag.Rating = rating;
                product.ProductRating = rating;
                db.SaveChanges();
            }
            else
            {
                ViewBag.RatingSum = 0;
                ViewBag.RatingCount = 0;
            }
            SetAccessRights();
            
            ViewBag.afisareButoane = false;
            if (User.IsInRole("Colaborator") || User.IsInRole("Admin"))
            {
                ViewBag.afisareButoane = true;
            }
            ViewBag.esteAdmin = User.IsInRole("Admin");
            ViewBag.esteColaborator = User.IsInRole("Colaborator");
            ViewBag.utilizatorCurent = User.Identity.GetUserId();

           
            return View(product);
        }
 
        [HttpPost]
        [Authorize(Roles = "User,Colaborator,Admin")]
        public ActionResult Show(Comment comm)
        {
            comm.Date = DateTime.Now;
            comm.UserId = User.Identity.GetUserId();
            try
            {
                if (ModelState.IsValid)
                {
                    float rating = 0;
                    Product a = db.Products.Find(comm.ProductId);
                    var ratings = db.Comments.Where(d => d.ProductId.Equals(comm.ProductId)).ToList();
                    if (ratings.Count() > 0)
                    {
                        var ratingSum = ratings.Sum(d => d.Rating.Value);
                        ViewBag.RatingSum = ratingSum;
                        var ratingCount = ratings.Count();
                        ViewBag.RatingCount = ratingCount;
                        rating = (ratingSum / ratingCount);
                        ViewBag.Rating = rating;
                        a.ProductRating = rating;
                    }
                    else
                    {   
                        ViewBag.RatingSum = 0;
                        ViewBag.RatingCount = 0;
                    }
                    db.Comments.Add(comm);
                    db.SaveChanges();
                    return Redirect("/Products/Show/" + comm.ProductId);
                   
                    
                }

                else
                {
                    Product a = db.Products.Find(comm.ProductId);
                    var ratings = db.Comments.Where(d => d.ProductId.Equals(comm.ProductId)).ToList();
                    if (ratings.Count() > 0)
                    {
                        var ratingSum = ratings.Sum(d => d.Rating.Value);
                        ViewBag.RatingSum = ratingSum;
                        var ratingCount = ratings.Count();
                        ViewBag.RatingCount = ratingCount;
                        var rating = (ratingSum / ratingCount);
                        a.ProductRating = rating;
                    }
                    else
                    {
                        ViewBag.RatingSum = 0;
                        ViewBag.RatingCount = 0;
                    }
                    SetAccessRights();
                    return View(a);
                }

            }

            catch (Exception e)
            {
                Product a = db.Products.Find(comm.ProductId);
                SetAccessRights();
                return View(a);
            }

        }
        

        // GET: New
        [Authorize(Roles = "Colaborator,Admin")]
        public ActionResult New()
        {
            Product product = new Product();

            // preluam lista de categorii din metoda GetAllCategories()
            product.Categ = GetAllCategories();

            // Preluam ID-ul utilizatorului curent
            product.UserId = User.Identity.GetUserId();
           
       
            return View(product);
        }

        // POST: New
        [HttpPost]
        [Authorize(Roles = "Colaborator,Admin")]
        public ActionResult New(Product product, HttpPostedFileBase uploadedFile)
        {
            product.Categ = GetAllCategories();
            //fara asta imi pune NULL in baza de date a Products la UserId
            product.UserId = User.Identity.GetUserId();

            try
            {
                if (ModelState.IsValid)
                {
                    string uploadedFileName = uploadedFile.FileName;
                    string uploadedFileExtension = Path.GetExtension(uploadedFileName);
                    if (uploadedFileExtension == ".png" || uploadedFileExtension == ".jpg" || uploadedFileExtension == ".pdf")
                    {
                        string uploadFolderPath = Server.MapPath("~//Files//");
                        uploadedFile.SaveAs(uploadFolderPath + uploadedFileName);
                        product.Photo = "/Files/" + uploadedFileName;
                    }
                    if (User.IsInRole("Admin"))
                        product.Request = true;
                    if (User.IsInRole("Colaborator"))
                        product.Request = false;
                    db.Products.Add(product);
                    db.Products.Add(product);
                    db.SaveChanges();
                    if (User.IsInRole("Admin"))

SweetsShop/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SweetsShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SweetsShop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = ApplicationDbContext.Create();
        // GET: Users
        public ActionResult Index()
        {
            var users = from user in db.Users
                        orderby user.UserName
                        select user;
            ViewBag.UsersList = users;

            return View();
        }
        public ActionResult Show(string id)
        {
            ApplicationUser user = db.Users.Find(id);

            ViewBag.utilizatorCurent = User.Identity.GetUserId();

            string currentRole = user.Roles.FirstOrDefault().RoleId;
            var userRoleName = (from role in db.Roles
                                where role.Id == currentRole
                                select role.Name).First();
            ViewBag.roleName = userRoleName;
            return View(user);
        }
        public ActionResult Edit(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            user.AllRoles = GetAllRoles();
            var userRole = user.Roles.FirstOrDefault();
            ViewBag.userRole = userRole.RoleId;
            return View(user);
        }
      
        [HttpPut]
        public ActionResult Edit(string id, ApplicationUser newData)
        {

            ApplicationUser user = db.Users.Find(id);
            user.AllRoles = GetAllRoles();
            var userRole = user.Roles.FirstOrDefault();
            ViewBag.userRole = userRole.RoleId;
            try
            {
                ApplicationDbContext context = new ApplicationDbContext();
                var roleManager = new RoleManager<IdentityRole>(new
               RoleStore<IdentityRole>(context));
                var UserManager = new UserManager<ApplicationUser>(new
               UserStore<ApplicationUser>(context));

                if (TryUpdateModel(user))
                {
                    user.UserName = newData.UserName;
                    user.Email = newData.Email;
                    user.PhoneNumber = newData.PhoneNumber;
                    var roles = from role in db.Roles select role;
                    foreach (var role in roles)
                    {
                        UserManager.RemoveFromRole(id, role.Name);
                    }
                    var selectedRole =
                    db.Roles.Find(HttpContext.Request.Params.Get("newRole"));
                    UserManager.AddToRole(id, selectedRole.Name);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                newData.Id = id;
                return View(newData);
            }

        }
        [NonAction]
        public IEnumerable<SelectListItem> GetAllRoles()
        {
            var selectList = new List<SelectListItem>();
            var roles = from role in db.Roles select role;
            foreach (var role in roles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = role.Id.ToString(),
                    Text = role.Name.ToString()
                });
            }
            return selectList;
        }
        [HttpDelete]
        public ActionResult Delete(string id)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var UserManager = new UserManager<ApplicationUser>(new
           UserStore<ApplicationUser>(context));
            var user = UserManager.Users.FirstOrDefault(u => u.Id == id);
            var products = db.Products.Where(a => a.UserId == id);
            foreach (var product in products)
            {
                db.Products.Remove(product);
            }
            var comments = db.Comments.Where(comm => comm.UserId == id);
            foreach (var comment in comments)
            {
                db.Comments.Remove(comment);
            }
            var orders = db.Orders.Where(ord => ord.UserId == id);
            foreach (var ord in orders)
            {
                db.Orders.Remove(ord);
            }
            db.SaveChanges();
            UserManager.Delete(user);
            return RedirectToAction("Index");
        }
    }
}

SweetsShop/Views/Shared/IndexProduct.cshtml
<div class="col-xs-6 row-style">

    <h1 class="font-roboto"> @Model.ProductName</h1>
    <p class="font-montserrat truncate">@Model.ProductPrice lei</p>
    <!-- rating eventual, -->
    <br />
    <img src=@Model.Photo width="300" height="300" />
    <br />

   
</div>

SweetsShop/Views/Shared/ProductInfo.cshtml
<div class="col-md-3">
    <div class="card text-center">
        <div class="card-block">
            <div class="card-header">
                <h3>
                    @Model.ProductName
                </h3>
            </div>
            <img class="card-img-top" src=@Model.Photo width="200px" height="180px">

            <div class="card-body">
                <h4 class="card-subtitle text-muted">
                    Categorie: @Model.Category.CategoryName
                </h4>
                @for (var i = 1; i <= Math.Floor(Model.ProductRating); i++)
                {
                    <span class="starGlowN"></span>
                }
                @for (var i = (Math.Floor(Model.ProductRating) + 1); i <= 5; i++)
                {
                    <span class="starFadeN"></span>
                }
                Pret: <strong> @Model.ProductPrice</strong> lei
                <br />
                <small>
                    Disponibilitate:
                    @if (Model.ProductStoc == 0)
                    {
                        @: nu sunt produse disponibile
                    }
                    else
                    if (Model.ProductStoc == 1)
                    {
                        @: un singur produs disponibil
                    }
                    else
                    {
                        <strong> @Model.ProductStoc</strong> @:produse disponibile
                    }
                </small>
                <br />


            </div>
        </div>
        <div class="clearfix">
            <a class="btn btn-sm btn-lg btn-success pull-left" style="background-color: #FD7272;" href="/Products/Show/@Model.ProductId"> 
            Afișare produs
            </a>


            @if (!User.IsInRole("Admin") && !User.IsInRole("Colaborator"))
            {
                using (Html.BeginForm(actionName: "Add", controllerName: "Orders", method: FormMethod.Post, routeValues: new { id = Model.ProductId }))
                {

                    <button class="btn btn-danger pull-right" style="background-color: #6D214F;" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                            <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0z"></path>
                        </svg>

                    </button>

                }
            }
        </div>

    </div>

</div>
            
       

    

SweetsShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sweets Shop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render("~/Content/Site.css")


</head>
<body>
    

     
        <div class="navbar navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">

                </div>

                <div class="navbar-collapse collapse">
                    <img src="~/Files/logogif.gif" class="pull-left" onclick="location.href='@Url.Action("Index", "Home")'" width="7%" />

                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Produse", "Index", "Products")</li>
                        <li>@Html.ActionLink("Categorii", "Index", "Categories")</li>

                        @if (User.IsInRole("Colaborator") || User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("+ produs", "New", "Products")</li>
                        }

                        @if (User.IsInRole("Admin"))
                        {

                            <li>@Html.ActionLink("+ categorie", "New", "Categories")</li>
                            <li>@Html.ActionLink("Utilizatori", "Index", "Users")</li>

                        }


                        @if (User.IsInRole("Admin"))
                        {
                            <li> @Html.ActionLink("Cereri", "Requests", "Products")</li>
                        }
                        @if (User.IsInRole("User"))
                        {
                            <li><a href="@Url.Action("MyCart", "Orders")" class="glyphicon glyphicon-shopping-cart"> Coș</a></li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>

        <div class="container body-content">
            @RenderBody()


        </div>
        <hr />
        <footer class="container-fluid bg-4 text-center">
            <p>&copy; @DateTime.Now.Year - Dima Oana & Bădescu Gabriel</p>
            <p>
                Ne găsiți pe:
                <a href="https://www.facebook.com/cofetariiledelice.ro"><img src="/Files/fb.png" width="5%" height="5%" /></a>
                <a href="https://www.instagram.com/cofetariile_delice/"><img src="/Files/insta.png" width="5%" height="5%" /></a>
            </p>

        </footer>


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>

</html>